
- name: restart zookeeper
  service: name=zookeeper-server state=restarted
  sudo: yes

- name: restart metastore
  service: name=hive-metastore state=restarted
  sudo: yes

- name: restart hive-server
  service: name=hive-server2 state=restarted
  sudo: yes
