---

- name: set mysql root password
  shell: echo mysql-server mysql-server/root_password password {{ mysql_root_password }} | sudo debconf-set-selections
  sudo: yes

- name: set mysql root password again
  shell: echo mysql-server mysql-server/root_password_again password  {{ mysql_root_password }} | sudo debconf-set-selections
  sudo: yes

- name: install mysql
  apt: pkg={{ item }}
  with_items:
    - mysql-server
    - python-mysqldb
  sudo: yes

- name: Start Mysql service
  service: name=mysql state=started

- name: set my.cnf
  template: src=my.cnf.j2 dest=/etc/mysql/my.cnf
  sudo: yes
  notify:
    - restart mysql