---

- name: Cloudera Repository
  apt_repository: repo="deb http://archive.cloudera.com/cdh4/debian/squeeze/amd64/cdh squeeze-cdh4.5.0 contrib" state=present
  sudo: yes

- name: Cloudera Src Repository
  apt_repository: repo="deb-src http://archive.cloudera.com/cdh4/debian/squeeze/amd64/cdh squeeze-cdh4.5.0 contrib" state=present
  sudo: yes

- name: Cloudera Apt-key
  apt_key: url="http://archive.cloudera.com/cdh4/debian/squeeze/amd64/cdh/archive.key" state=present
  sudo: yes

- name: apt update
  apt: update_cache=yes
  sudo: yes
